`timescale 1ns / 1ps
`include "game_definitions.vh"

//==============================================================================
// top_game - Top-Level Game Integration Module
//==============================================================================
// Purpose:
//   This is the top-level integration module for the maze-based treasure hunt
//   game. It coordinates all game subsystems including the finite state machine,
//   level management, player movement, collision detection, VGA display, and
//   score display.
//
// Architecture Overview:
//   - FSM Coordination: The game_fsm module manages game progression through
//     three levels and a win state based on player reaching goal positions.
//   - Level Multiplexing: Three level modules (level1, level2, level3) provide
//     maze layout data. Metadata and wall information are dynamically selected
//     based on the current level_select signal from the FSM.
//   - Movement Control: Button inputs drive player movement with collision
//     detection against maze walls. Player position is tracked in screen
//     coordinates and mapped to tile grid coordinates.
//   - Display Pipeline: VGA output is managed through the drawcon module for
//     normal gameplay and a dedicated win screen ROM for the victory state.
//   - Score Display: A 7-segment display shows the current score (0-3)
//     corresponding to treasures collected across levels.
//
// Data Flow:
//   1. Button inputs -> Movement logic -> Player position (blkpos_x, blkpos_y)
//   2. Player position -> Tile coordinate calculation -> current_row, current_col
//   3. current_row/col -> FSM -> level_select output (determines current level)
//   4. level_select -> Level mux -> Active level metadata and wall data
//   5. Wall data + movement request -> Collision detection -> Position update
//   6. Player position + level_select -> drawcon -> VGA RGB outputs
//   7. level_select -> score_counter -> score -> 7-segment decoder
//
// Clock Domains:
//   - System Clock (clk): 100MHz input from board, used for game logic and
//     clock generation
//   - Pixel Clock (pixclk): Generated by PLL (clk_wiz_0) for VGA timing
//   - Game Clock (game_clk): Divided from system clock (~500Hz) for player
//     movement timing
//
// Reset Behavior:
//   - Asynchronous active-low reset (rst)
//   - When rst=0: All state machines reset, player returns to starting position,
//     game returns to LEVEL1, score resets to 0
//   - Reset is propagated to all submodules (FSM, score counter, VGA, drawcon)
//==============================================================================

module top_game(
    input clk,
    input rst,
    input [4:0] btn,
    output [3:0] pix_r,
    output [3:0] pix_g,
    output [3:0] pix_b,
    output hsync,
    output vsync,
    output reg a, b, c, d, e, f, g               
);

    // Local parameters for derived constants
    localparam INFOBAR_HEIGHT = `INFO_H * `INFO_SCALE;  // 25 * 4 = 100 pixels

    //==========================================================================
    // Clock Generation and Division
    //==========================================================================
    // This section generates the necessary clock signals for the game:
    //
    // 1. Pixel Clock (pixclk):
    //    - Generated by the Xilinx PLL (clk_wiz_0) IP core
    //    - Required for VGA timing and pixel rendering
    //    - Input: 100MHz system clock
    //
    // 2. Game Clock (game_clk):
    //    - Divided from the 100MHz system clock for movement timing
    //    - Divider: `GAME_CLK_DIV (200,000 cycles) creates ~500Hz clock
    //    - This slower clock controls player movement speed (updates position
    //      at ~500Hz when buttons are pressed)
    //    - Synchronous reset: Resets divider and clock state when rst=0
    //==========================================================================

    // Pixel clock for VGA timing
    wire pixclk;
    clk_wiz_0 pll (.clk_out1(pixclk), .clk_in1(clk));

    // Game clock divider (creates ~500Hz game tick from 100MHz system clock)
    reg [20:0] clk_div;
    reg game_clk;
    always @(posedge clk) begin
        if (!rst) begin
            clk_div <= 0;
            game_clk <= 0;
        end else if (clk_div == `GAME_CLK_DIV) begin
            clk_div <= 0;
            game_clk <= ~game_clk;
        end else begin
            clk_div <= clk_div + 1;
        end
    end

    //==========================================================================
    // Game State Machine and Player Tracking
    //==========================================================================
    // FSM-Movement Relationship:
    //   The game_fsm monitors the player's tile position (current_row, current_col)
    //   to determine when goal positions are reached. When a goal is reached, the
    //   FSM advances level_select to the next level (`LEVEL1 -> `LEVEL2 -> `LEVEL3
    //   -> `WIN_STATE). The level_select signal feeds back into the movement logic
    //   to select the appropriate level metadata and wall configuration.
    //
    // Player State Variables:
    //   - blkpos_x, blkpos_y: Player screen position in pixels (absolute coordinates)
    //   - current_row, current_col: Player's current tile position in the maze grid
    //   - adj_row, adj_col: Adjacent tile position (for collision detection)
    //   - x_in_tile, y_in_tile: Player position relative to current tile origin
    //   - prev_level: Tracks previous level to detect level transitions
    //
    // Score Tracking:
    //   The score_counter module tracks treasures collected (0-3) based on reaching
    //   specific tile positions across all three levels. Score is displayed on the
    //   7-segment display.
    //==========================================================================

    // Player position state
    reg [10:0] blkpos_x = 11'd394;  // Initial X position (centered in level)
    reg [10:0] blkpos_y = 11'd141;  // Initial Y position (INFOBAR_HEIGHT + 41px offset)
    reg [4:0] current_row, current_col, adj_row, adj_col;  // Tile coordinates
    reg [9:0] x_in_tile, y_in_tile;  // Position within current tile
    reg [1:0] prev_level = `LEVEL1;  // Track level changes

    // FSM outputs
    wire [1:0] level_select;  // Current level (`LEVEL1, `LEVEL2, `LEVEL3, or `WIN_STATE)
    wire win;                 // High when win state reached

    // Game finite state machine (manages level progression)
    game_fsm fsm_inst (
        .clk(game_clk),
        .rst(rst),
        .player_row(current_row),
        .player_col(current_col),
        .level_select(level_select),
        .win(win)
    );

    // Score tracking (0-3 treasures collected)
    wire [7:0] score;
    score_counter score_logic (
        .clk(game_clk),
        .rst(rst),
        .level_select(level_select),
        .player_row(current_row),
        .player_col(current_col),
        .score(score)
    );


    //==========================================================================
    // 7-Segment Display - Score Display Logic
    //==========================================================================
    // This section decodes the score value (0-3) into 7-segment display signals.
    // The display shows the number of treasures collected across all levels:
    //   - Score 0: Display '0' (start of game)
    //   - Score 1: Display '1' (after completing level 1)
    //   - Score 2: Display '2' (after completing level 2)
    //   - Score 3: Display '3' (after completing level 3)
    //
    // Segment encoding: a-g correspond to the standard 7-segment layout
    // Logic is active-low (0 = segment ON, 1 = segment OFF)
    //
    //     a
    //   f   b
    //     g
    //   e   c
    //     d
    //==========================================================================
    always @(*) begin
        case (score)
            8'd0: begin
                // Display '0': All segments ON except g (middle)
                a = 0; b = 0; c = 0; d = 0; e = 0; f = 0; g = 1;
            end
            8'd1: begin
                // Display '1': Only right side segments (b, c)
                a = 1; b = 0; c = 0; d = 1; e = 1; f = 1; g = 1;
            end
            8'd2: begin
                // Display '2': a, b, d, e, g (classic 2 shape)
                a = 0; b = 0; c = 1; d = 0; e = 0; f = 1; g = 0;
            end
            8'd3: begin
                // Display '3': a, b, c, d, g (classic 3 shape)
                a = 0; b = 0; c = 0; d = 0; e = 1; f = 1; g = 0;
            end
            default: begin
                // Blank display (should not occur in normal gameplay)
                a = 0; b = 0; c = 0; d = 0; e = 0; f = 0; g = 0;
            end
        endcase
    end

    //==========================================================================
    // Level Instantiation and Metadata Multiplexing
    //==========================================================================
    // This section instantiates all three level modules and multiplexes their
    // outputs based on the current level_select signal from the FSM.
    //
    // Level Module Responsibilities:
    //   Each level module (level1, level2, level3) provides:
    //   - Maze layout data: Wall configuration for each tile (4-bit: T, B, L, R)
    //   - Metadata: TILE_W, TILE_H, NUM_ROWS, NUM_COLS, WALL_MARGIN
    //
    // Instantiation Pattern:
    //   - Metadata instances: Query with row=0, col=0 to fetch level constants
    //   - Current tile instances: Query player's current tile for wall data
    //   - Adjacent tile instances: Query adjacent tile for collision detection
    //
    // Multiplexing Logic:
    //   The level_select signal (from FSM) drives two multiplexers:
    //   1. Metadata Mux: Selects active level's TILE_W, TILE_H, etc.
    //   2. Wall Data Mux: Selects wall configuration for current and adjacent tiles
    //
    // Wall Encoding (4-bit):
    //   walls[3] = Top wall present
    //   walls[2] = Bottom wall present
    //   walls[1] = Left wall present
    //   walls[0] = Right wall present
    //==========================================================================

    // Level 1 metadata and wall data
    wire [9:0] TILE_W1, TILE_H1, WALL_MARGIN1;
    wire [4:0] NUM_ROWS1, NUM_COLS1;
    wire [3:0] dummy1;
    level1 l1info (.row(5'd0), .col(5'd0), .walls(dummy1), .TILE_W(TILE_W1), .TILE_H(TILE_H1), .NUM_ROWS(NUM_ROWS1), .NUM_COLS(NUM_COLS1), .WALL_MARGIN(WALL_MARGIN1));

    // Level 2 metadata and wall data
    wire [9:0] TILE_W2, TILE_H2, WALL_MARGIN2;
    wire [4:0] NUM_ROWS2, NUM_COLS2;
    wire [3:0] dummy2;
    level2 l2info (.row(5'd0), .col(5'd0), .walls(dummy2), .TILE_W(TILE_W2), .TILE_H(TILE_H2), .NUM_ROWS(NUM_ROWS2), .NUM_COLS(NUM_COLS2), .WALL_MARGIN(WALL_MARGIN2));

    // Level 3 metadata and wall data
    wire [9:0] TILE_W3, TILE_H3, WALL_MARGIN3;
    wire [4:0] NUM_ROWS3, NUM_COLS3;
    wire [3:0] dummy3;
    level3 l3info (.row(5'd0), .col(5'd0), .walls(dummy3), .TILE_W(TILE_W3), .TILE_H(TILE_H3), .NUM_ROWS(NUM_ROWS3), .NUM_COLS(NUM_COLS3), .WALL_MARGIN(WALL_MARGIN3));

    // Multiplexed level metadata (selected by level_select)
    reg [9:0] TILE_W, TILE_H, WALL_MARGIN;
    reg [4:0] NUM_ROWS, NUM_COLS;

    // Metadata multiplexer: Select active level's configuration
    // level_select values: `LEVEL1 (2'd0), `LEVEL2 (2'd1), `LEVEL3 (2'd2), `WIN_STATE (2'd3)
    always @(*) begin
        case (level_select)
            `LEVEL1: begin 
                // Level 1 configuration
                TILE_W = TILE_W1; 
                TILE_H = TILE_H1; 
                NUM_ROWS = NUM_ROWS1; 
                NUM_COLS = NUM_COLS1; 
                WALL_MARGIN = WALL_MARGIN1; 
            end
            `LEVEL2: begin 
                // Level 2 configuration
                TILE_W = TILE_W2; 
                TILE_H = TILE_H2; 
                NUM_ROWS = NUM_ROWS2; 
                NUM_COLS = NUM_COLS2; 
                WALL_MARGIN = WALL_MARGIN2; 
            end
            `LEVEL3: begin 
                // Level 3 configuration
                TILE_W = TILE_W3; 
                TILE_H = TILE_H3; 
                NUM_ROWS = NUM_ROWS3; 
                NUM_COLS = NUM_COLS3; 
                WALL_MARGIN = WALL_MARGIN3; 
            end
            default: begin 
                // Win state or invalid: Use safe defaults
                TILE_W = 10'd0; 
                TILE_H = 10'd0; 
                NUM_ROWS = 5'd0; 
                NUM_COLS = 5'd0; 
                WALL_MARGIN = 10'd0; 
            end
        endcase
    end

    // Wall data for collision detection (current and adjacent tiles for all levels)
    wire [3:0] walls_curr_l1, walls_adj_l1, walls_curr_l2, walls_adj_l2, walls_curr_l3, walls_adj_l3;
    
    // Level 1 wall queries
    level1 l1_cur (.row(current_row), .col(current_col), .walls(walls_curr_l1), .TILE_W(), .TILE_H(), .NUM_ROWS(), .NUM_COLS(), .WALL_MARGIN());
    level1 l1_adj (.row(adj_row),     .col(adj_col),     .walls(walls_adj_l1),  .TILE_W(), .TILE_H(), .NUM_ROWS(), .NUM_COLS(), .WALL_MARGIN());
    
    // Level 2 wall queries
    level2 l2_cur (.row(current_row), .col(current_col), .walls(walls_curr_l2), .TILE_W(), .TILE_H(), .NUM_ROWS(), .NUM_COLS(), .WALL_MARGIN());
    level2 l2_adj (.row(adj_row),     .col(adj_col),     .walls(walls_adj_l2),  .TILE_W(), .TILE_H(), .NUM_ROWS(), .NUM_COLS(), .WALL_MARGIN());
    
    // Level 3 wall queries
    level3 l3_cur (.row(current_row), .col(current_col), .walls(walls_curr_l3), .TILE_W(), .TILE_H(), .NUM_ROWS(), .NUM_COLS(), .WALL_MARGIN());
    level3 l3_adj (.row(adj_row),     .col(adj_col),     .walls(walls_adj_l3),  .TILE_W(), .TILE_H(), .NUM_ROWS(), .NUM_COLS(), .WALL_MARGIN());

    // Multiplexed wall data for collision detection
    reg [3:0] wall_curr_mux, wall_adj_mux;

    // Wall data multiplexer: Select active level's wall configuration
    // wall_curr_mux = walls at player's current tile
    // wall_adj_mux = walls at adjacent tile (in direction of movement)
    always @(*) begin
        case (level_select)
            `LEVEL1: begin 
                wall_curr_mux = walls_curr_l1; 
                wall_adj_mux = walls_adj_l1; 
            end
            `LEVEL2: begin 
                wall_curr_mux = walls_curr_l2; 
                wall_adj_mux = walls_adj_l2; 
            end
            `LEVEL3: begin 
                wall_curr_mux = walls_curr_l3; 
                wall_adj_mux = walls_adj_l3; 
            end
            default: begin 
                // Win state: No walls (allow free movement or freeze)
                wall_curr_mux = 4'd0; 
                wall_adj_mux = 4'd0; 
            end
        endcase
    end

    //==========================================================================
    // Player Movement and Wall Collision Detection
    //==========================================================================
    // This section handles player movement based on button inputs and enforces
    // collision detection with maze walls.
    //
    // Movement Logic Flow:
    //   1. Calculate player's current tile position (current_row, current_col)
    //      from absolute screen coordinates (blkpos_x, blkpos_y)
    //   2. Determine position within tile (x_in_tile, y_in_tile) for collision
    //   3. Calculate adjacent tile coordinates based on button input direction
    //   4. Check for wall collision in movement direction
    //   5. Update position if no collision detected
    //
    // Special Conditions:
    //   - Win state: Freeze player position (no movement allowed)
    //   - Level transition: Reset player to starting position (394, 141)
    //   - Reset or center button: Return player to starting position
    //
    // Movement Speed:
    //   - Player moves `MOVE_STEP_SIZE (2) pixels per game_clk tick (~500Hz)
    //   - Movement is synchronized to game_clk for consistent speed
    //
    // Reset Behavior:
    //   - Synchronous reset on game_clk (not asynchronous)
    //   - When rst=0: Player position resets to (394, 141)
    //==========================================================================
    always @(posedge game_clk) begin
        if (win) begin
            // Win state: Freeze player at current position
            blkpos_x <= blkpos_x;
            blkpos_y <= blkpos_y;
        end else if (level_select != prev_level) begin
            // Level transition detected: Reset player to starting position
            blkpos_x <= 11'd394;  // Center X for 1440-wide level (288*5)
            blkpos_y <= 11'd141;  // INFOBAR_HEIGHT + 41px into first tile
            prev_level <= level_select;
        end else if (!rst || btn[0]) begin
            // Reset or center button pressed: Return to start
            blkpos_x <= 11'd394;  // Center X
            blkpos_y <= 11'd141;  // INFOBAR_HEIGHT + 41px
        end else begin
            // Normal gameplay: Handle movement and collision
            prev_level <= level_select;

            // Convert screen coordinates to tile coordinates
            current_col = blkpos_x / TILE_W;
            current_row = (blkpos_y - INFOBAR_HEIGHT) / TILE_H;  // Subtract infobar height
            x_in_tile   = blkpos_x % TILE_W;
            y_in_tile   = (blkpos_y - INFOBAR_HEIGHT) % TILE_H;

            // Initialize adjacent tile to current tile
            adj_col = current_col;
            adj_row = current_row;

            // Determine adjacent tile based on button input direction
            // (Used for collision detection when crossing tile boundaries)
            case (btn[4:1])
                4'b0001: if (current_row > 0) adj_row = current_row - 1;                  // UP
                4'b1000: if (current_row < NUM_ROWS - 1) adj_row = current_row + 1;       // DOWN
                4'b0010: if (current_col > 0) adj_col = current_col - 1;                  // LEFT
                4'b0100: if (current_col < NUM_COLS - 1) adj_col = current_col + 1;       // RIGHT
            endcase

            //======================================================================
            // Wall Collision Detection and Movement Update
            //======================================================================
            // For each direction, check if the next position would collide with:
            //   1. Wall in current tile (wall_curr_mux[direction])
            //   2. Wall in adjacent tile (wall_adj_mux[opposite_direction])
            //
            // Movement is prevented if:
            //   - Current tile has a wall in movement direction AND
            //   - Player sprite edge is within WALL_MARGIN of tile edge
            //   OR
            //   - Adjacent tile has a wall opposite to movement direction AND
            //   - Player sprite edge is within WALL_MARGIN of tile edge
            //
            // If no collision, update position by `MOVE_STEP_SIZE pixels
            //======================================================================
            case (btn[4:1])
                4'b0001: begin  // UP movement
                    // Check top wall of current tile or bottom wall of tile above
                    // Collision if: (current has top wall AND near top edge) OR (above has bottom wall AND near top edge)
                    if (!(wall_curr_mux[3] && y_in_tile <= WALL_MARGIN || 
                          wall_adj_mux[2] && y_in_tile <= WALL_MARGIN)) 
                        blkpos_y <= blkpos_y - `MOVE_STEP_SIZE;
                end
                4'b1000: begin  // DOWN movement
                    // Check bottom wall of current tile or top wall of tile below
                    // Collision if: (current has bottom wall AND sprite bottom near tile bottom) OR (below has top wall)
                    if (!(wall_curr_mux[2] && y_in_tile + `BLK_SIZE_Y >= TILE_H - WALL_MARGIN || 
                          wall_adj_mux[3] && y_in_tile + `BLK_SIZE_Y >= TILE_H - WALL_MARGIN)) 
                        blkpos_y <= blkpos_y + `MOVE_STEP_SIZE;
                end
                4'b0010: begin  // LEFT movement
                    // Check left wall of current tile or right wall of tile to the left
                    // Collision if: (current has left wall AND near left edge) OR (left has right wall AND near left edge)
                    if (!(wall_curr_mux[1] && x_in_tile <= WALL_MARGIN || 
                          wall_adj_mux[0] && x_in_tile <= WALL_MARGIN)) 
                        blkpos_x <= blkpos_x - `MOVE_STEP_SIZE;
                end
                4'b0100: begin  // RIGHT movement
                    // Check right wall of current tile or left wall of tile to the right
                    // Collision if: (current has right wall AND sprite right edge near tile right) OR (right has left wall)
                    if (!(wall_curr_mux[0] && x_in_tile + `BLK_SIZE_X >= TILE_W - WALL_MARGIN || 
                          wall_adj_mux[1] && x_in_tile + `BLK_SIZE_X >= TILE_W - WALL_MARGIN)) 
                        blkpos_x <= blkpos_x + `MOVE_STEP_SIZE;
                end
            endcase
        end
    end


    //==========================================================================
    // VGA Display Pipeline and Win Screen
    //==========================================================================
    // This section manages the display output through two rendering paths:
    //
    // 1. Normal Gameplay (win=0):
    //    - drawcon module generates RGB values for maze, player, and UI
    //    - Displays current level, walls, player sprite, and infobar
    //
    // 2. Win Screen (win=1):
    //    - Displays "YOU WIN!" image from ROM (400x100 pixels)
    //    - Image centered at screen position (120, 200)
    //    - Black background outside image area
    //
    // Display Multiplexing:
    //    - win signal selects between normal gameplay and win screen
    //    - RGB outputs synchronized to pixel clock
    //
    // VGA Timing:
    //    - vga module generates sync signals and coordinates (curr_x, curr_y)
    //    - Operates on pixel clock (pixclk) from PLL
    //    - Standard 640x480 @ 60Hz timing
    //==========================================================================

    // VGA coordinate outputs and RGB signals
    wire [10:0] curr_x, curr_y;
    wire [3:0] draw_r, draw_g, draw_b;

    // Normal gameplay RGB outputs from drawcon
    wire [3:0] draw_r_normal, draw_g_normal, draw_b_normal;
    
    // Drawing controller for normal gameplay (maze, player, UI)
    drawcon drawcon_inst (
        .blkpos_x(blkpos_x),
        .blkpos_y(blkpos_y),
        .clk(clk),
        .rst(rst),
        .level_select(level_select),
        .draw_r(draw_r_normal),
        .draw_g(draw_g_normal),
        .draw_b(draw_b_normal),
        .curr_x(curr_x),
        .curr_y(curr_y)
    );
    
    //==========================================================================
    // Win Screen - Victory Image Display
    //==========================================================================
    // When win=1, display "YOU WIN!" image from ROM
    // Image specifications:
    //   - Size: 400x100 pixels (WIN_IMG_W x WIN_IMG_H)
    //   - Screen position: X=[120, 519], Y=[200, 299]
    //   - Horizontal centering: (`SCREEN_WIDTH - 400) / 2 = (640-400)/2 = 120
    //   - Vertical position: 200 (adjusted from mathematical center for aesthetics)
    //     Mathematical center would be: (`SCREEN_HEIGHT - 100) / 2 = (480-100)/2 = 190
    //==========================================================================
    
    // Win image dimensions (not defined in game_definitions.vh)
    localparam WIN_IMG_W = 400;     // Win image width in pixels
    localparam WIN_IMG_H = 100;     // Win image height in pixels
    localparam WIN_X_POS = 120;     // X position (horizontally centered)
    localparam WIN_Y_POS = 200;     // Y position (vertically positioned)
    
    reg [15:0] win_pixel_addr;  // ROM address for win screen image
    wire [11:0] win_pixel;       // 12-bit RGB pixel data from ROM
    reg [3:0] draw_r_reg, draw_g_reg, draw_b_reg;  // Registered RGB outputs
    
    // Connect registered outputs to VGA module
    assign draw_r = draw_r_reg;
    assign draw_g = draw_g_reg;
    assign draw_b = draw_b_reg;
    
    // Display multiplexer: Select between normal gameplay and win screen
    always @(posedge clk) begin
        if (win) begin
            // Win state: Display "YOU WIN!" image
            if (curr_y >= WIN_Y_POS && curr_y < (WIN_Y_POS + WIN_IMG_H) && 
                curr_x >= WIN_X_POS && curr_x < (WIN_X_POS + WIN_IMG_W)) begin
                // Inside win image area: Calculate ROM address
                // Address = (row * width) + col = (y-WIN_Y_POS)*WIN_IMG_W + (x-WIN_X_POS)
                win_pixel_addr <= (curr_y - WIN_Y_POS) * WIN_IMG_W + (curr_x - WIN_X_POS);
                draw_r_reg <= win_pixel[11:8];  // Red component
                draw_g_reg <= win_pixel[7:4];   // Green component
                draw_b_reg <= win_pixel[3:0];   // Blue component
            end else begin
                // Outside win image area: Black background
                draw_r_reg <= 4'd0;
                draw_g_reg <= 4'd0;
                draw_b_reg <= 4'd0;
            end
        end else begin
            // Normal gameplay: Use drawcon outputs
            draw_r_reg <= draw_r_normal;
            draw_g_reg <= draw_g_normal;
            draw_b_reg <= draw_b_normal;
        end
    end
    
    // Win screen ROM instance (stores "YOU WIN!" image)
    you_win_rom win_screen_inst (
        .addra(win_pixel_addr),
        .clka(clk),
        .douta(win_pixel)
    );

    //==========================================================================
    // VGA Controller - Sync Signal Generation
    //==========================================================================
    // Generates VGA timing signals (hsync, vsync) and pixel coordinates
    // Operates on pixel clock for proper VGA timing (640x480 @ 60Hz)
    //==========================================================================
    vga vga_inst (
        .clk(pixclk),
        .rst(rst),
        .draw_r(draw_r),
        .draw_g(draw_g),
        .draw_b(draw_b),
        .curr_x(curr_x),
        .curr_y(curr_y),
        .pix_r(pix_r),
        .pix_g(pix_g),
        .pix_b(pix_b),
        .hsync(hsync),
        .vsync(vsync)
    );

endmodule
